###
GET http://localhost:3000/api/v1/characters

###
POST http://localhost:3000/api/v1/characters
content-Type: application/json

{
  "name": "Ashley",
  "nickname": "Ash",
  "age": 1000,
  "race": "Elf",
  "favoriteColor": "Ocre"
}
